export const START_TEST_REQUEST = "START_TEST_REQUEST";
export const START_TEST_SUCCESS = "START_TEST_SUCCESS";
export const START_TEST_FAIL = "START_TEST_FAIL";
export const START_TEST_RESET = "START_TEST_RESET";

export const GENERATE_RESULT_REQUEST = "GENERATE_RESULT_REQUEST";
export const GENERATE_RESULT_SUCCESS = "GENERATE_RESULT_SUCCESS";
export const GENERATE_RESULT_FAIL = "GENERATE_RESULT_FAIL";
export const GENERATE_RESULT_RESET = "GENERATE_RESULT_RESET";
